My_Second_Project/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
app_name = 'Login_app'


urlpatterns= [
    path('', views.index, name= "index"),
    path('register/', views.register, name= "register"),
    path('login/', views.login_page, name= "login"),
    path('user_login/', views.user_login, name= "user_login"),
    path('logout/', views.user_logout, name= "logout"),
    ]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Second_Project/My_Second_Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

My_Second_Project/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

My_Second_Project/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model = UserInfo
        fields = ('facebook_id','profile_pic')

My_Second_Project/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserInfoForm,UserForm
from django.contrib.auth.models import User
from Login_app.models import UserInfo

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.

def login_page(request):
    dist = {}
    return render(request,'Login_app/login.html',context=dist)

def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
                # return render(request, 'Login_app/index.html',context={})
                # return index(request)
            else:
                return HttpResponse("Account is not active!!")
        else:
            return HttpResponse("Login details are wrong!!")
    else:
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:index'))


def index(request):
    dict = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__pk=user_id)
        
        dict.update({'user_basic_info':user_basic_info,"user_more_info":user_more_info})
    return render(request,'Login_app/index.html',context=dict)

def register(request):

    registerd = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password) #encript password
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user 

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            
            user_info.save()

            registerd = True

    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    dict = {'user_form':user_form,"user_info_form":user_info_form,"registerd":registerd}
    return render(request,'Login_app/register.html',context=dict)

My_Second_Project/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />

    <title>{{title}}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href=" {% url 'Login_app:index' %}"
            >Home</a
          >
        </li>
        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href=" {% url 'Login_app:logout' %}">Logout</a>
        </li>
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href=" {% url 'Login_app:register' %}"
            >Registration</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href=" {% url 'Login_app:login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>

    <div class="container" style="padding-top: 20px">
      {% block body_block %} {% endblock body_block %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

My_Second_Project/templates/Login_app/index.html
{% extends 'Login_app/base.html' %} {% block body_block %} 
{% if user.is_authenticated %} 

<p> hi {{user_basic_info.username}} </p>
<p>email:  {{user_basic_info.email}}  </p>
<br>
 <p>dp: {{user_more_info.profile_pic}}</p>
 <p>fb id:{{user_more_info.facebook_id}}</p>
<img src="/media/{{user_more_info.profile_pic}}" width="200px" alt="">


 {% else %}

<div class="alert alert-primary">You are not logged in!</div>

{% endif %} {% endblock body_block %}

My_Second_Project/templates/Login_app/login.html
{% extends 'Login_app/base.html' %} {% block body_block %}
<h3>Please Login:</h3>
<form method="POST" action="{% url 'Login_app:user_login' %}">
  <label for="username">Username: </label>
  <input
    type="text"
    name="username"
    placeholder="Enter Username "
    required
    class="form-control"
  />
  <label for="password">Password: </label>
  <input
    type="text"
    name="password"
    placeholder="Enter Password "
    required
    class="form-control"
  />
  <br />
  <input type="submit" name="submit" value="Login" />
  {% csrf_token %}
</form>

{% endblock body_block %}

My_Second_Project/templates/Login_app/register.html
{% extends 'Login_app/base.html' %} {% block body_block %}
{% if registerd %}
<p>Hello</p>
<div class="alert alert-success">Congratulations! Registration Successful</div>
{% else %}
 <form enctype="multipart/form-data" method="POST"> 
 <p>Hello no</p>
  {{user_form.as_p}}
  {{user_info_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Register"/>
</form>

{% endif %} 
{% endblock %}